services:
    'FL\GmailBundle\Action\SaveAccessTokenAction':
        class: FL\GmailBundle\Action\SaveAccessTokenAction
        arguments:
          - "@router"
          - "@fl_gmail.token_file_storage"

    'FL\GmailBundle\Action\AuthoriseGoogleAction':
        class: FL\GmailBundle\Action\AuthoriseGoogleAction
        arguments:
          - "@fl_gmail.unauthorised_client"
