services:
    'FL\GmailBundle\Action\AuthoriseGoogleAction':
        class: FL\GmailBundle\Action\AuthoriseGoogleAction
        arguments:
          - "@fl_gmail.unauthorised_client"

    'FL\GmailBundle\Action\SaveAuthorisationAction':
        class: FL\GmailBundle\Action\SaveAuthorisationAction
        arguments:
          - "@router"
          - "@fl_gmail.credentials_storage_service"
          - "%fl_gmail.redirect_route_after_save_authorisation%"