language: php

matrix:
  include:
    - php: 7.1
      env: SWIFT_VERSION=~6.0.0
    - php: 7.1
      env: SWIFT_VERSION=~5.4.0

before_script:
  - composer require "swiftmailer/swiftmailer:${SWIFT_VERSION}" --no-update
  - composer install --no-interaction --dev
